version: "3.2"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  flask-simple:
    build:
      dockerfile: Dockerfile1
      context: .
    command: python app.py
    volumes:
      - ./src:/usr/src/app/
      - ./src/static/upload/:/usr/src/app/upload
      
  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db
      - ./dump:/dump
    ports:
      - "27018:27017"
      
volumes:
  mongodata:
